<?php

namespace PiDev\GestionCategorie\CategorieBundle\Repository;

/**
 * InteretRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InteretRepository extends \Doctrine\ORM\EntityRepository
{
}
