pi_dev_gestion_publicite_publicite_homepage:
    path:     /
    defaults: { _controller: PiDevGestionPublicitePubliciteBundle:Default:index }
ajoutpublicite:
    path:     /ajoutpublicite
    defaults: { _controller: PiDevGestionPublicitePubliciteBundle:Publicite:ajout }
affichepublicite:
    path:     /affichepublicite
    defaults: { _controller: PiDevGestionPublicitePubliciteBundle:Publicite:affiche }

likepublicite2:
    path:     /likepublicite
    defaults: { _controller: PiDevGestionPublicitePubliciteBundle:Publicite:like }
dislikepublicite2:
    path:     /dislikepublicite
    defaults: { _controller: PiDevGestionPublicitePubliciteBundle:Publicite:dislike }

deletepublicite:
    path:     /deletepublicite
    defaults: { _controller: PiDevGestionPublicitePubliciteBundle:Publicite:delete }
updatepublicite:
    path:     /updatepublicite
    defaults: { _controller: PiDevGestionPublicitePubliciteBundle:Publicite:updatepublicite }
recherchepublicite:
    path:     /recherchepublicite
    defaults: { _controller: PiDevGestionPublicitePubliciteBundle:Publicite:recherche }

findcontenue:
    path:     /recherche1publicite
    defaults: { _controller: PiDevGestionPublicitePubliciteBundle:Publicite:recherchecontenuDQL }
findcat:
    path:     /recherchercat
    defaults: { _controller: PiDevGestionPublicitePubliciteBundle:Publicite:recherchecat }
findcategorie:
    path:     /recherchecategorieDQL
    defaults: { _controller: PiDevGestionPublicitePubliciteBundle:Publicite:recherchecategorieDQL }



findlieu:
    path:     /recherchelieuDQL
    defaults: { _controller: PiDevGestionPublicitePubliciteBundle:Publicite:recherchelieuDQL }

affpubmo:
    path:     /affpubmo
    defaults: { _controller: PiDevGestionPublicitePubliciteBundle:Publicite:affichepubmo}


lik11:
    path:     /lik1/{id}/{idu}
    defaults: { _controller: PiDevGestionPublicitePubliciteBundle:Publicite:lik}

dislik11:
    path:     /dislik1/{id}/{idu}
    defaults: { _controller: PiDevGestionPublicitePubliciteBundle:Publicite:Dislik}
pubaa:
    path:     /mespu/{idu}
    defaults: { _controller: PiDevGestionPublicitePubliciteBundle:Publicite:mespub }
profite:
    path:     /profite/{id}/{idu}
    defaults: { _controller: PiDevGestionPublicitePubliciteBundle:Publicite:profiter1}
findlieucat:
    path:     /recherchelieucatDQL
    defaults: { _controller: PiDevGestionPublicitePubliciteBundle:Publicite:recherchelieucat }
accepter:
    path:     /accepterpub
    defaults: { _controller: PiDevGestionPublicitePubliciteBundle:Publicite:accepter }

refuser:
    path:     /refuserpub
    defaults: { _controller: PiDevGestionPublicitePubliciteBundle:Publicite:refuser }
ajoutoffre:
    path:     /ajoutoffre
    defaults: { _controller: PiDevGestionPublicitePubliciteBundle:Offre:ajoutoffre }
deleteoffre:
    path:     /deleteoffre
    defaults: { _controller: PiDevGestionPublicitePubliciteBundle:Offre:deleteoffre }
updateoffre:
    path:     /updateoffre
    defaults: { _controller: PiDevGestionPublicitePubliciteBundle:Offre:updateoffre }
afficheoffre:
    path:     /afficheoffre
    defaults: { _controller: PiDevGestionPublicitePubliciteBundle:Offre:afficheoffre }
afficheoffre1:
    path:     /afficheoffre1
    defaults: { _controller: PiDevGestionPublicitePubliciteBundle:Offre:afficheoffre1 }
findcategorie1:
    path:     /recherchelieuDQL
    defaults: { _controller: PiDevGestionPublicitePubliciteBundle:Publicite:recherchecategorieDQL }

profiterpublicite:
    path:     /profiterpublicite
    defaults: { _controller: PiDevGestionPublicitePubliciteBundle:Publicite:profiter }

affiche11:
    path:     /Afficherpub1/{idpublicite}
    defaults: { _controller: PiDevGestionPublicitePubliciteBundle:Publicite:Afficherpub1 }

Afficherprofituser:
    path:     /Afficherprofituser
    defaults: { _controller: PiDevGestionPublicitePubliciteBundle:Publicite:Afficherprofituser }

valider:
    path:     /valider
    defaults: { _controller: PiDevGestionPublicitePubliciteBundle:Publicite:valider }