<?php

namespace PiDev\GestionReclamation\ReclamationBundle\Repository;

/**
 * FeedbackRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FeedbackRepository extends \Doctrine\ORM\EntityRepository
{
    public function calculmoyenne()
    {
        $query = $this->getEntityManager()->createQuery(
            "select AVG(v.note) from PiDevGestionReclamationReclamationBundle:notesite v    ");
        return  $query->getSingleScalarResult();
    }
}
