<?php
/**
 * Created by PhpStorm.
 * User: Marwa
 * Date: 19/02/2019
 * Time: 12:53
 */

namespace PiDev\GestionEvenement\EvenementBundle\Repository;
/**
 * ParticipationEvenementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */


class CommentEvenementRepository extends \Doctrine\ORM\EntityRepository
{

}