<?php
/**
 * Created by PhpStorm.
 * User: Marwa
 * Date: 16/02/2019
 * Time: 20:56
 */

namespace PiDev\GestionEvenement\EvenementBundle\Repository;


use Doctrine\ORM\EntityRepository;

/**
 * EvenementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvenementRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByevent($idevenement){
        $query = $this->createQueryBuilder('m')
            ->where('m.idevenement = :param')
            ->setParameter('param',$idevenement);
        return $query->getQuery()->getResult();
    }


    public function findContenuParametre($nomevenement){
        $query = $this->getEntityManager()
            ->createQuery("SELECT p FROM PiDevGestionEvenementEvenementBundle:Evenement p where p.nomevenement LIKE :nomevenement")
            ->setParameter('nomevenement','%'.$nomevenement.'%');
        return $query->getResult();
    }





}