<?php

namespace PiDev\GestionEvenement\EvenementBundle\Repository;

/**
 * ParticipationEvenementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParticipationEvenementRepository extends \Doctrine\ORM\EntityRepository
{
}
