<?php

namespace PiDev\GestionConcours\ConcoursBundle\Repository;

/**
 * ConcoursRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConcoursRepository extends \Doctrine\ORM\EntityRepository
{
    public function findDateDebut()
    {
        $query = $this->getEntityManager()
            ->createQuery("SELECT c FROM PiDevGestionConcoursConcoursBundle:Concours c 
                          where c.datedebut <= CURRENT_DATE()
                          AND c.datefin >= CURRENT_DATE() "  );
        return $query->getResult();

    }
}
