<?php

namespace PiDev\GestionConcours\ConcoursBundle\Repository;

/**
 * ParticipationConcoursRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParticipationConcoursRepository extends \Doctrine\ORM\EntityRepository
{
}
