<?php

namespace PiDev\GestionPublicite\PubliciteBundle\Repository;

/**
 * codepromoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class codepromoRepository extends \Doctrine\ORM\EntityRepository
{
}
