<?php

namespace PiDev\GestionPublication\PublicationBundle\Repository;

/**
 * like_dislikeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class like_dislikeRepository extends \Doctrine\ORM\EntityRepository
{
}
