<?php

namespace PiDev\GestionPublication\PublicationBundle\Repository;

/**
 * listeamisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class listeamisRepository extends \Doctrine\ORM\EntityRepository
{
}
