<?php

namespace PiDev\GestionVente\VenteBundle\Repository;

/**
 * ReactionProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReactionProduitRepository extends \Doctrine\ORM\EntityRepository
{
}
